SELECT uu.USER_ID, uu.NICKNAME, CONCAT(uu.CITY,' ',uu.STREET_ADDRESS1,' ',uu.STREET_ADDRESS2) 전체주소,
INSERT(
INSERT(uu.TLNO, 4, 0, '-'), 
9, 0, '-'
) 전화번호
FROM USED_GOODS_BOARD ub
INNER JOIN USED_GOODS_USER uu
ON ub.WRITER_ID = uu.USER_ID
GROUP BY ub.WRITER_ID
HAVING COUNT(ub.WRITER_ID) >= 3
ORDER BY uu.USER_ID DESC;
