SELECT ai.ANIMAL_ID, ai.ANIMAL_TYPE, ai.NAME
FROM ANIMAL_INS ai
INNER JOIN ANIMAL_OUTS ao
ON ai.ANIMAL_ID = ao.ANIMAL_ID
WHERE SUBSTRING(ai.SEX_UPON_INTAKE,1,6) = "Intact" AND SUBSTRING(ao.SEX_UPON_OUTCOME,1,6) != "Intact"
ORDER BY ai.ANIMAL_ID