SELECT YEAR(os.SALES_DATE) AS YEAR, MONTH(os.SALES_DATE) AS MONTH, ui.GENDER, COUNT(DISTINCT(ui.USER_ID)) AS USERS
FROM USER_INFO ui
INNER JOIN ONLINE_SALE os
ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;

# SELECT *
# FROM USER_INFO ui
# INNER JOIN ONLINE_SALE os
# ON ui.USER_ID = os.USER_ID
# WHERE MONTH(os.SALES_DATE) = '1';