# 자동차의 여러 대여 기록 중에
# 2022-10-16일날 대여중인 자동차는 대여 중이라고 하고
# 그 날에 대여중이 아닌 모든 자동차는 대여 가능
SELECT CAR_ID,
CASE WHEN CAR_ID IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') THEN '대여중'
ELSE '대여 가능' END
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;