SELECT ap.APNT_NO, pa.PT_NAME, pa.PT_NO, doc.MCDP_CD, doc.DR_NAME, ap.APNT_YMD
FROM DOCTOR doc
INNER JOIN APPOINTMENT ap 
ON doc.DR_ID = ap.MDDR_ID
INNER JOIN PATIENT pa 
ON ap.PT_NO = pa.PT_NO
WHERE SUBSTRING(ap.APNT_YMD,1,10) = '2022-04-13'
AND ap.APNT_CNCL_YN = 'N' AND doc.MCDP_CD = 'CS'
ORDER BY ap.APNT_YMD ASC;
