# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (PRODUCT_NAME, PRICE) IN(
# SELECT PRODUCT_NAME, MAX(PRICE)
# FROM FOOD_PRODUCT 
# GROUP BY CATEGORY)


# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT


SELECT f.CATEGORY, m.MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT AS f
INNER JOIN
(SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT 
GROUP BY CATEGORY) AS m
ON f.CATEGORY = m.CATEGORY AND f.PRICE = m.MAX_PRICE
WHERE f.CATEGORY IN ("김치","국","식용유","과자")
ORDER BY 2 DESC;